### ISSUE TITLE
Main cointainer 100vh

### ISSUE THREAD

**Issue by norbi945** [zemkogabor/admin-layout-vue#3]
A main container mindig a content méretéhez alkalmazkodik. Ha pl van egy datepicker, akkor megeshet, hogy nem rajzolódik ki rendesen.
Lehetne a main 100vh-s.
Megpróbáltam felüírni :deep-el és akkor az overflow is hidden lett. (Csak info)

**Comment by zemkogabor** [comment]
Töröltem a overflow hidden-t (ez megoldja a datepicker/dropdown levágást alacsony magasságú oldalaknál), viszont a 100vh magasságot egyelőre nem raknám a libbe. Nem vagyok biztos benne, hogy lenne gyakorlati haszna. De ha igen, akkor valahogy így csinálnám:

```
.main {
  // ...
  min-height: calc(100vh - $navbar-top-height);
}
```

https://github.com/zemkogabor/admin-layout-vue/commit/56263d420cac6258ca3c612753f72214b443f459
